name: UbuntuStrategy
on: [push, pull_request]
jobs:
  build:
    name: UbuntuStrategy
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix: 
        go: [1.1, 1.2]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 50
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Download
      run: |
  postgres-2:
    name: UbuntuStrategy
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, E, S, D, F, G, H, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2, 3, 4, 5, 6, 7, 8]
    timeout-minutes: 55
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: CheckoutV2_mboge
      uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v1
      with: 
        python-version: 3.8
    - name: Install Library
      run : pip install selenium
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
    - name: chmod geckodriver
      run: chmod +x geckodriver
    - name: Run
      run: python salika.py
